# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP005():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP005(self):
    self.driver.get("http://localhost/control/login.php")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.NAME, "user_name").send_keys("admin")
    self.driver.find_element(By.NAME, "user_password").send_keys("admin")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-2:nth-child(1) .img-responsive").click()
    self.driver.find_element(By.LINK_TEXT, "Editar").click()
    self.driver.find_element(By.ID, "mod_nombre").click()
    self.driver.find_element(By.ID, "mod_nombre").send_keys("Clavo cemento")
    self.driver.find_element(By.ID, "actualizar_datos").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myModal2 .btn-default").click()
    self.driver.find_element(By.LINK_TEXT, "Salir").click()
  
