# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP004():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP004(self):
    self.driver.get("http://localhost/control/login.php")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("admin")
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.NAME, "user_password").send_keys("aaaa")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("admi")
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.NAME, "user_password").send_keys("sadasd")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("sadasd")
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.NAME, "user_password").send_keys("sadas")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("sadasd")
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.NAME, "user_password").send_keys("sadasd")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("dfsfsdg")
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.NAME, "user_password").send_keys("dsfsdf")
    self.driver.find_element(By.ID, "submit").click()
  
