# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP001():
  def setup_method(self, method): 
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP001(self):
    self.driver.get("http://localhost/control/login.php")
    self.driver.set_window_size(974, 1040)
    self.driver.find_element(By.NAME, "user_name").send_keys("admin")
    self.driver.find_element(By.NAME, "user_password").send_keys("admin")
    self.driver.find_element(By.NAME, "user_name").click()
    self.driver.find_element(By.NAME, "user_password").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "codigo").click()
    self.driver.find_element(By.ID, "codigo").send_keys("C001")
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").send_keys("Clavo")
    self.driver.find_element(By.ID, "categoria").click()
    dropdown = self.driver.find_element(By.ID, "categoria")
    dropdown.find_element(By.XPATH, "//option[. = 'Herramientas']").click()
    self.driver.find_element(By.ID, "precio").click()
    self.driver.find_element(By.ID, "precio").send_keys("500")
    self.driver.find_element(By.ID, "stock").click()
    self.driver.find_element(By.ID, "stock").send_keys("200")
    self.driver.find_element(By.ID, "guardar_datos").click()
    self.driver.find_element(By.CSS_SELECTOR, "#nuevoProducto .btn-default").click()
    self.driver.find_element(By.LINK_TEXT, "Salir").click()
    self.driver.find_element(By.NAME, "user_name").send_keys("admin")
    self.driver.find_element(By.NAME, "user_password").send_keys("admin")
  
